export const featuredProducts = [
  {
    id: "f1",
    title: "Pepperoni Classico",
    desc: "A circular pizza topped with spicy beef pepperoni, fresh tomato slices, and melted mozzarella — a timeless favorite with a bold twist.",
    img: "/photo1.png",
    price: 27.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 5 },
      { title: "Large", additionalPrice: 7 },
    ],
  },
  {
    id: "f2",
    title: "Zesty Mint Pizza",
    desc: "Freshly baked pepperoni pizza with vibrant mint leaves and a touch of house-made secret sauce for an unforgettable fusion of flavors.",
    img: "/photo2.png",
    price: 28.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 5 },
      { title: "Large", additionalPrice: 7 },
    ],
  },
  {
    id: "f3",
    title: "Salmon Greens",
    desc: "A refreshing arugula salad with red onions, sumac, cherry tomatoes, and a grilled salmon slice on top — light, tangy, and rich in flavor.",
    img: "/photo3.png",
    price: 34.9,
    options: [
      { title: "Regular", additionalPrice: 0 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "f4",
    title: "BBQ Drumsticks",
    desc: "Tender chicken drumsticks glazed in sweet and smoky BBQ sauce — juicy, flavorful, and grilled to perfection.",
    img: "/photo5.png",
    price: 32.9,
    options: [
      { title: "3 Pieces", additionalPrice: 0 },
      { title: "6 Pieces", additionalPrice: 6 },
      { title: "9 Pieces", additionalPrice: 10 },
    ],
  },
  {
    id: "f5",
    title: "BBQ Chicken Pizza",
    desc: "Juicy grilled chicken pieces layered on a crispy crust with rich BBQ sauce, mozzarella, and a hint of smokiness in every bite.",
    img: "/photo4.png",
    price: 31.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 5 },
      { title: "Large", additionalPrice: 7 },
    ],
  },
  {
    id: "f6",
    title: "Fettuccine Alfredo",
    desc: "Rich and creamy pasta tossed with Parmesan cheese and butter, garnished with parsley for a smooth and velvety flavor.",
    img: "/photo6.png",
    price: 20.5,
    options: [
      { title: "1 Skewer", additionalPrice: 0 },
      { title: "2 Skewers", additionalPrice: 5 },
      { title: "3 Skewers", additionalPrice: 8 },
    ],
  },
  {
    id: "f7",
    title: "Rustic Pomodoro",
    desc: "Traditional pasta in rich tomato sauce with garlic, basil, Parmesan, cherry tomatoes, and bell pepper slices — a comforting Italian classic.",
    img: "/photo7.png",
    price: 26.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "f8",
    title: "Veggie Lovers Pizza",
    desc: "Thin crust pizza topped with mozzarella cheese, black olives, mushrooms, and fresh oregano — a cheesy vegetarian delight.",
    img: "/photo8.png",
    price: 28.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 5 },
      { title: "Large", additionalPrice: 7 },
    ],
  },
];

export const burgers = [
  {
    id: "b1",
    title: "Classic Cheeseburger",
    desc: "Juicy beef patty topped with melted cheddar cheese, lettuce, tomato, pickles, and our special sauce on a toasted bun.",
    img: "/burger1.png",
    price: 12.5,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 4 },
      { title: "Triple", additionalPrice: 7 },
    ],
  },
  {
    id: "b2",
    title: "Bacon BBQ Burger",
    desc: "Smoky BBQ sauce, crispy bacon, cheddar cheese, and onion rings stacked on a juicy beef patty.",
    img: "/burger2.png",
    price: 14.0,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 4 },
      { title: "Triple", additionalPrice: 7 },
    ],
  },
  {
    id: "b3",
    title: "Mushroom Swiss Burger",
    desc: "Sautéed mushrooms, Swiss cheese, caramelized onions, and garlic aioli on a tender beef patty.",
    img: "/burger3.png",
    price: 13.5,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 4 },
      { title: "Triple", additionalPrice: 7 },
    ],
  },
  {
    id: "b4",
    title: "Spicy Burger",
    desc: "Pepper jack cheese, jalapeños, spicy mayo, lettuce, and tomato on a flame-grilled beef patty.",
    img: "/burger4.png",
    price: 13.0,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 4 },
      { title: "Triple", additionalPrice: 7 },
    ],
  },
  {
    id: "b5",
    title: "Veggie Burger",
    desc: "Delicious plant-based patty with lettuce, tomato, avocado, and vegan mayo on a whole grain bun.",
    img: "/burger5.png",
    price: 11.0,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 3 },
      { title: "Triple", additionalPrice: 6 },
    ],
  },
  {
    id: "b6",
    title: "Mediterranean Lamb Burger",
    desc: "Juicy lamb patty infused with herbs, topped with feta cheese, cucumber slices, red onions, and tzatziki sauce on a grilled bun.",

    img: "/burger6.png",
    price: 14.5,
    options: [
      { title: "Single", additionalPrice: 0 },
      { title: "Double", additionalPrice: 4 },
      { title: "Triple", additionalPrice: 7 },
    ],
  },
];

export const pizzas = [
  {
    id: "p1",
    title: "Pepperoni Classico",
    desc: "A circular pizza topped with spicy beef pepperoni, fresh tomato slices, and melted mozzarella — a timeless favorite with a bold twist.",
    img: "/photo1.png",
    price: 27.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "p2",
    title: "Zesty Mint Pizza",
    desc: "Freshly baked pepperoni pizza with vibrant mint leaves and a touch of house-made secret sauce for an unforgettable fusion of flavors.",
    img: "/photo2.png",
    price: 28.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "p3",
    title: "BBQ Chicken Pizza",
    desc: "Juicy grilled chicken pieces layered on a crispy crust with rich BBQ sauce, mozzarella, and a hint of smokiness in every bite.",
    img: "/photo4.png",
    price: 31.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "p4",
    title: "Veggie Lovers Pizza",
    desc: "Thin crust pizza topped with mozzarella cheese, black olives, mushrooms, and fresh oregano — a cheesy vegetarian delight.",
    img: "/photo8.png",
    price: 28.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "p5",
    title: "Mushroom Cherry Delight",
    desc: "A flavorful fusion of sautéed mushrooms, juicy cherry tomatoes, and creamy mozzarella on a crisp Italian crust — simple, fresh, and utterly satisfying.",
    img: "/pizza5.png",
    price: 24.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
  {
    id: "p6",
    title: "Spicy Veggie Rounds",
    desc: "Colorful veggie goodness topped with red plant-based sausage-style rounds, sweet bell peppers, olives, and melty cheese on a golden baked crust — bold and delicious!",
    img: "/pizza6.png",
    price: 22.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 4 },
      { title: "Large", additionalPrice: 6 },
    ],
  },
];
export const italians = [
  {
    id: "i1",
    title: "Rustic Pomodoro",
    desc: "Traditional pasta in rich tomato sauce with garlic, basil, Parmesan, cherry tomatoes, and bell pepper slices — a comforting Italian classic.",
    img: "/photo7.png",
    price: 26.9,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 3 },
      { title: "Large", additionalPrice: 5 },
    ],
  },
  {
    id: "i2",
    title: "Fettuccine Alfredo",
    desc: "Rich and creamy pasta tossed with Parmesan cheese and butter, garnished with parsley for a smooth and velvety flavor.",
    img: "/photo6.png",
    price: 20.5,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 3 },
      { title: "Large", additionalPrice: 5 },
    ],
  },
  {
    id: "i3",
    title: "Penne Arrabbiata",
    desc: "Spicy pasta dish made with garlic, tomatoes, and red chili peppers, offering a bold and fiery flavor.",
    img: "/pasta3.png",
    price: 19.5,
    options: [
      { title: "Small", additionalPrice: 0 },
      { title: "Medium", additionalPrice: 3 },
      { title: "Large", additionalPrice: 5 },
    ],
  },
];

export const menu = [
  {
    id: 11,
    slug: "italians",
    title: "Italian Pastas",
    desc: "Savor the taste of perfection with our exquisite Italian handmade pasta menu.",
    img: "/m1.png",
    color: "white",
  },
  {
    id: 22,
    slug: "burgers",
    title: "Juicy Burgers",
    desc: "Burger Bliss: Juicy patties, bold flavors, and gourmet toppings galore.",
    img: "/m2.png",
    color: "black",
  },
  {
    id: 33,
    slug: "pizzas",
    title: "Cheesy Pizzas",
    desc: "Pizza Paradise: Irresistible slices, mouthwatering toppings, and cheesy perfection.",
    img: "/m3.png",
    color: "white",
  },
];export const galleryImages = [
  {
    id: 1,
    imageUrl: "/user1.png",
    userName: "Rania H.",
    caption: "Can’t get enough of this burger! 🍔",
    date: "01-07-2025",
  },
  {
    id: 2,
    imageUrl: "/user2.png",
    userName: "Zaid A.",
    caption: "Caught the perfect pizza shot! 📸🍕",
    date: "02-07-2025",
  },
  {
    id: 3,
    imageUrl: "/user3.png",
    userName: "Nadine M.",
    caption: "My kids loved every bite of the pizza!",
    date: "03-07-2025",
  },
  {
    id: 4,
    imageUrl: "/user4.png",
    userName: "Reham R.",
    caption: "We all loved the food here!",
    date: "04-07-2025",
  },
  {
    id: 5,
    imageUrl: "/user5.png",
    userName: "Sally K.",
    caption: "The salad was so fresh 🥗",
    date: "05-07-2025",
  },
  {
    id: 6,
    imageUrl: "/user6.png",
    userName: "Mira Y.",
    caption: "Best burger I’ve had in a while!",
    date: "06-07-2025",
  },
  {
    id: 7,
    imageUrl: "/user7.png",
    userName: "Laila J.",
    caption: "Pasta perfection 😍🍝",
    date: "07-07-2025",
  },
  {
    id: 8,
    imageUrl: "/user8.png",
    userName: "Omar S.",
    caption: "Crispy fried chicken done right 🔥",
    date: "08-07-2025",
  },
  {
    id: 9,
    imageUrl: "/user9.png",
    userName: "Nour T.",
    caption: "Going crazy for this burger! 🤤",
    date: "09-07-2025",
  },
  {
    id: 10,
    imageUrl: "/user10.png",
    userName: "Dana L.",
    caption: "Pizza night with friends 🍕🎉",
    date: "10-07-2025",
  },
  {
    id: 11,
    imageUrl: "/user11.png",
    userName: "Tamer F.",
    caption: "This chicken is so good!",
    date: "11-07-2025",
  },
  {
    id: 12,
    imageUrl: "/user12.png",
    userName: "Maya R.",
    caption: "Yummy and juicy burger 😋",
    date: "12-07-2025",
  },
];
